### PR TITLE
Feature 679 managing header/footer size

### PR DESCRIPTION
**Pull request by BrennenFa**
I added a useEffect that would check the size of the current window and use it to dynamically resize the header and footer to match the screen size.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.246.177.202:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.246.177.202:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by YazidZidane** [comment]
The implementation is working well, I think you can make `useWindowSize()` a custom hook and then we can use it anywhere!

**Comment by Adamws33** [comment]
> The implementation is working well, I think you can make `useWindowSize()` a custom hook and then we can use it anywhere!

@BrennenFa I sent you some information about custom hooks in react.  Let me know if you'd like to discuss this any further.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,20.246.177.202,:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
