### PR TITLE
removed bootstrap

### PR DESCRIPTION
**Pull request by ameyachavan007**
remove bootstrap implementation and unnecessary styling files for information sheet references

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
can you `npm uninstall bootstrap` to make sure everything was removed?

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,20.253.76.68,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
still a bootstrap class in goalTag line 58. related to above error

**Comment by mikahpinegar** [comment]
still a bootstrap class in header.js line 247

**Comment by mikahpinegar** [comment]
still a bootstrap class in constants.js line 66

**Comment by ameyachavan007** [comment]
> unselected goals showing wrong icon
> 
> goals_icon

*resolved*

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,20.253.76.68,:,80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by ameyachavan007** [comment]
> still a bootstrap class in header.js line 247

*Resolved*

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://20.253.76.68:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by ameyachavan007** [comment]
> still a bootstrap class in constants.js line 66

*Resolved*

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
