### PR TITLE
updated constants.js

### PR DESCRIPTION
**Pull request by ameyachavan007**
updated constants.js so that comparison table can hold multiple values in each cell

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://57.151.42.227:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://57.151.42.227:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
crashes for midwest

**Comment by ameyachavan007** [comment]
> crashes for midwest

image
@mikahpinegar is the case for all midwest states? let me know if there is an exception(where cover crop group in midwest is not undefined) so that I can test this fix.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,57.151.42.227:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://57.151.42.227:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
