### PR TITLE
More user history

### PR DESCRIPTION
**Pull request by YazidZidane**
- Finished integrating user history with the rest of the app.
- The save function will trigger when user switching page(not include Landing to Location), and when the history is newly created or updated.

This pr contains changes from #623 .

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,51.8.5.226,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
this crashes on initial load with the following error
```
HistorySelect.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at HistorySelect (HistorySelect.js:123:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
```

**Comment by mikahpinegar** [comment]
can we reuse the modal from the seeding rate calculator? i think it looks busy having the history buttons below the state selection in the landing page

**Comment by mikahpinegar** [comment]
filtering crops isn't working. any selected filter removes all crops

**Comment by mikahpinegar** [comment]
the comparison view is not extracting data properly anymore
comparson view

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,51.8.5.226,:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
this is very hard to read. is there an issue with using a modal like for the seeding rate calculator? i think they should either both use modals or both use selections like you have here 
hard to read

**Comment by YazidZidane** [comment]
> this is very hard to read. is there an issue with using a modal like for the seeding rate calculator? i think they should either both use modals or both use selections like you have here hard to read

This looks very different from my updates. It looks like the `HistorySelect` component is not correctly updated. Attached my updates below:
image
image

**Comment by mikahpinegar** [comment]
i've pulled down all the changes that are committed to this branch

**Comment by mikahpinegar** [comment]
do i need to run `npm i`?

**Comment by mikahpinegar** [comment]
can you move the buttons into the box above the map in the landing page?

**Comment by mikahpinegar** [comment]
can you add text between the state dropdown and the history buttons that says `Try out our new user history feature below` if logged in and `Log in to try out our new user history feature` if not logged in

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
clicking next and then back from landing gives the below error. i'm getting a 4222 response from the history api and the following error in the app
```
Cannot read properties of undefined (reading 'data')
TypeError: Cannot read properties of undefined (reading 'data')
    at http://localhost:3000/static/js/bundle.js:10894:17
```

**Comment by mikahpinegar** [comment]
i think there may be a bug with the popup far resetting cover crop list. if i add a few crops to my list from the explorer and then refresh and import a history the crops show up correctly but if i click browse cover crops it warns me that i have to reset. are you storing the flag needed for this popup in the user history?

**Comment by mikahpinegar** [comment]
another possible bug with the reset crops modal: if i make a fresh history and then navigate to the explore, then add a couple crops, then try to go back to the landing it tells me i need to reset crops. is this the desired behavior or should it happen when you click next and start the get a recommendation flow?

**Comment by Adamws33** [comment]
> > another possible bug with the reset crops modal: if i make a fresh history and then navigate to the explore, then add a couple crops, then try to go back to the landing it tells me i need to reset crops. is this the desired behavior or should it happen when you click next and start the get a recommendation flow?
> 
> I think this is existed before. It forbids user from changing the states after selecting crops in the explorer.

i can confirm.  This was created to reset as you exited from one section (Recommendation or explorer) to the other because a user could add crops to my cover crop list then navigate to the recommendation section and select a new state that might not have those same crops.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.5.226:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,51.8.5.226,:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by YazidZidane** [comment]
> i think there may be a bug with the popup far resetting cover crop list. if i add a few crops to my list from the explorer and then refresh and import a history the crops show up correctly but if i click browse cover crops it warns me that i have to reset. are you storing the flag needed for this popup in the user history?

This should be fixed with the new commit.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
