### PR TITLE
Feature/calendar view updates

### PR DESCRIPTION
**Pull request by Adamws33**
updated the calendar view 
removed initial title "cover crop growing window"
Moved legend to sidebar
re designed sidebar
added sorting arrows
added column title highlight on sort
added checkbox on selected images.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by YazidZidane — COMMENTED** [review]
I think overall these changes look pretty great. I have a few thoughts: 

- Firstly can you add some gap between the `crop list` and `crop calendar` button and the crop calendar? 
- Secondly I think the position of arrow for sorting column is reversed. Also I'm not sure if we should show this as a default, is there a sorting order for the initial crop window?

Also I think the calendar doesn't fit in the mobile view well, but this is not for this pr.

**Comment by Adamws33** [comment]
> I think overall these changes look pretty great. I have a few thoughts:
> 
> * Firstly can you add some gap between the `crop list` and `crop calendar` button and the crop calendar?
> * Secondly I think the position of arrow for sorting column is reversed. Also I'm not sure if we should show this as a default, is there a sorting order for the initial crop window?
> 
> Also I think the calendar doesn't fit in the mobile view well, but this is not for this pr.

i will add in that space i meant to and totally spaced it. 

I will double check the arrow direction on each column pointing down to should be like a-z or 1-9 i believe so i will make sure that is true. 
the initial sort is on average goal rating which we used to have a sort button for but no longer do.  so currently there is no arrow to display on initial load.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://172.171.82.9:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by YazidZidane — APPROVED** [review]

**Pull request merged**
