### PR TITLE
fix pipeline conflicts between branches

### PR DESCRIPTION
**Pull request by drewlearns**
Pipeline for production was failing to deploy - this was the most logical way I could figure to enable 2 different ingresses. fingers crossed it works.

### CODE REVIEW

**Review by mikahpinegar — APPROVED** [review]

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.231.118.197:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.231.118.197:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.231.118.197:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.231.118.197:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
