### PR TITLE
Brennen button styling

### PR DESCRIPTION
**Pull request by BrennenFa**
Attempting to fix Issue #651 by creating homogenous button styling

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.0.120:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,135.237.0.120:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
please follow branch naming conventions listed in this doc https://precision-sustainable-ag.atlassian.net/wiki/spaces/ON/pages/156270593/Branching+Strategies

**Comment by mikahpinegar** [comment]
instead of styling all the buttons individually, can you make a button component that defines the styling once and then use that everywhere a button is used? this will make it so you don't have to redefine the styles in so many places

**Comment by BrennenFa** [comment]
I did not intend to make changes to eslint or gitignore. Is there anything I should do about the changes I made?

Also, I will attempt to make the new button type. Would you like me to make one button component for the top 3 buttons and a separate one for the bottom two (crop list, crop calendar)? The bottom two rely on a boolean to change color if one is selected

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.0.120:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.0.120:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Pull request closed without merging**
