### PR TITLE
finished refactor of informationBar also refactored Location and impl…

### PR DESCRIPTION
**Pull request by Adamws33**
Refactor of InformationBar and Location

added new global component BinaryButton to handle yes or no type prompts.

### CODE REVIEW

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.232.53.144:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.232.53.144:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
the info bar is missing the soil drainage class

**Comment by mikahpinegar** [comment]
nevermind, that only happened when i input chicago instead of a specific address

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
