### PR TITLE
Issue67: Moved legend modal to seperate component

### PR DESCRIPTION
**Pull request by dearpriyankasa**
THE ISSUE AND THE TASKS DONE IN THE PR
Current issue: currently the word Legend blends into the title bar, the modal takes on the same grey color as the background and the logic for the legend is built into the CropTable file and should be its own component: RESOLVED

Stretch goal: if you are able to quickly resolve the background color issue please do: RESOLVED

### CODE REVIEW

**Comment by mikahpinegar** [comment]
will you add a pr description and update the last updated time in the readme?

**Comment by mikahpinegar** [comment]
also the modal is still grayed out

**Comment by dearpriyankasa** [comment]
> will you add a pr description and update the last updated time in the readme?

I added the PR desc, I did not understand the readme part, what exactly do i need to do there?

**Comment by Adamws33** [comment]
> > will you add a pr description and update the last updated time in the readme?
> 
> I added the PR desc, I did not understand the readme part, what exactly do i need to do there?

On the 5th line of the readme we have a last date modified date.  just change that to today's date.  Thank you!!

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
