### PR TITLE
Weather conditions component & others: Refactoring

### PR DESCRIPTION
**Pull request by dearpriyankasa**
1. Logically segregated the components into different files
2. Solved the faded weather edit modal issue
3. LocationConfirmation.js file: Removed extra ternaries
4. CropSelectorCalendarView.js file: Segregated out the paint growth component

### CODE REVIEW

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://,20.237.97.55,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://,20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by Adamws33 — APPROVED** [review]

**Comment by mikahpinegar** [comment]
editing frost free days is broken

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.237.97.55:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
