### PR TITLE
Fix frontend crop value parsing

### PR DESCRIPTION
**Pull request by YazidZidane**
Fixed value parsing problems on crop calendar view, crop card from browser and crop comparison view

Edit: search `.values` to find these places where are parsing crop attributes

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,4.157.15.79,:,80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,4.157.15.79:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
clicking through to the calendar view is throwing this error
```
dateArray.split is not a function
TypeError: dateArray.split is not a function
    at http://localhost:3000/static/js/bundle.js:21146:36
    at Array.forEach (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:21138:19
    at Array.forEach (<anonymous>)
    at monthStringBuilder (http://localhost:3000/static/js/bundle.js:21137:23)
    at http://localhost:3000/static/js/bundle.js:21180:31
    at Array.map (<anonymous>)
    at cropDataFormatter (http://localhost:3000/static/js/bundle.js:21180:19)
    at http://localhost:3000/static/js/bundle.js:6991:77
```

**Comment by YazidZidane** [comment]
> clicking through to the calendar view is throwing this error
> 
> ```
> dateArray.split is not a function
> TypeError: dateArray.split is not a function
>     at http://localhost:3000/static/js/bundle.js:21146:36
>     at Array.forEach (<anonymous>)
>     at http://localhost:3000/static/js/bundle.js:21138:19
>     at Array.forEach (<anonymous>)
>     at monthStringBuilder (http://localhost:3000/static/js/bundle.js:21137:23)
>     at http://localhost:3000/static/js/bundle.js:21180:31
>     at Array.map (<anonymous>)
>     at cropDataFormatter (http://localhost:3000/static/js/bundle.js:21180:19)
>     at http://localhost:3000/static/js/bundle.js:6991:77
> ```

I'm not having this issue on this branch, but I do face this error on the most recent user history pr and got it fixed. Can you try that branch to see if this error still exists?

**Comment by mikahpinegar** [comment]
i don't see any new commits on that branch

**Comment by YazidZidane** [comment]
I mean it's already fixed in that branch

**Comment by mikahpinegar** [comment]
does that branch contain the changes from these two prs?

**Comment by YazidZidane** [comment]
> does that branch contain the changes from these two prs?

It has the changes of this branch, and it's based on the previous user history branch

**Pull request closed without merging**
