### PR TITLE
Feature/goal sorting

### PR DESCRIPTION
**Pull request by Adamws33**
Updated sorting to work more properly and added goal sorting

### CODE REVIEW

**Comment by mikahpinegar** [comment]
there's a conflict that needs to be resolved

**Comment by mikahpinegar** [comment]
picking a location in the map doesn't update county dropdown

**Comment by mikahpinegar** [comment]
plant hardiness zone in the explorer should be changed to a dropdown

**Comment by mikahpinegar** [comment]
search in the explorer is broken for midwest

**Comment by mikahpinegar** [comment]
filtering crops is broken for the midwest

**Comment by mikahpinegar** [comment]
need to add fly free dates like how they have here https://www.midwestcovercrops.org/covercroptool. to recreate select Illinois, Christian county, Good Grazing and scroll down

**Comment by Adamws33** [comment]
> need to add fly free dates like how they have here https://www.midwestcovercrops.org/covercroptool. to recreate select Illinois, Christian county, Good Grazing and scroll down

@mikahpinegar This issue cannot yet be fixed.  While i can see where the fly-free attribute is inside some crops there is not a description or a date associated it it to operate like the Midwest's site is working.  

The rest of the tasks are done and ready to be reviewed.

**Comment by mikahpinegar** [comment]
filtering is still broken for mccc

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
