### PR TITLE
Add snackbar message for user history

### PR DESCRIPTION
**Pull request by YazidZidane**
- Added message for user history loading, saving and error.
- Updated user history api structure.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by Adamws33** [comment]
The first alert says "your location has been saved" and all of the rest say "History Updated".  Can we update each of them to be a more clear message for what has just been updated?

**Comment by Adamws33** [comment]
One thing i noticed is that when i add crops from the browse and then hit restart and recall that history the crops i added are included in the history.  But if i go through the get a recommendation and i add crops i still get the alert "[crop name] was added" but the crops are not getting saved to my history unless i navigate away from the page to my list before restarting.

**Comment by Adamws33** [comment]
I think this may be a bug from the user history and not from this ticket but something i found. 
I went to create a new history, then selected Ohio, then selected Browse Cover Crops then selected 3 random crops.  I then hit the get a recommendation button which then forces a reset and when i went to go select the history i created i noticed all of my histories were gone. A refresh of the page corrected things and the history saved as expected. 
image

**Comment by YazidZidane** [comment]
> The first alert says "your location has been saved" and all of the rest say "History Updated". Can we update each of them to be a more clear message for what has just been updated?

> One thing i noticed is that when i add crops from the browse and then hit restart and recall that history the crops i added are included in the history. But if i go through the get a recommendation and i add crops i still get the alert "[crop name] was added" but the crops are not getting saved to my history unless i navigate away from the page to my list before restarting.

Currently the history is only saved upon page change so if you don't switch the page it will not be saved, and thus all of the snackbar message says 'History saved/updated', except for the location one which is already existed before.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by Adamws33** [comment]
> > The first alert says "your location has been saved" and all of the rest say "History Updated". Can we update each of them to be a more clear message for what has just been updated?
> 
> > One thing i noticed is that when i add crops from the browse and then hit restart and recall that history the crops i added are included in the history. But if i go through the get a recommendation and i add crops i still get the alert "[crop name] was added" but the crops are not getting saved to my history unless i navigate away from the page to my list before restarting.
> 
> Currently the history is only saved upon page change so if you don't switch the page it will not be saved, and thus all of the snackbar message says 'History saved/updated', except for the location one which is already existed before.
> 
> Edit: I do found a way to trigger save user history upon select crops, should I add them when a crop is added?

Yes please.  That way it is consistent with the browse section too

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by YazidZidane** [comment]
> > > The first alert says "your location has been saved" and all of the rest say "History Updated". Can we update each of them to be a more clear message for what has just been updated?
> > 
> > 
> > > One thing i noticed is that when i add crops from the browse and then hit restart and recall that history the crops i added are included in the history. But if i go through the get a recommendation and i add crops i still get the alert "[crop name] was added" but the crops are not getting saved to my history unless i navigate away from the page to my list before restarting.
> > 
> > 
> > Currently the history is only saved upon page change so if you don't switch the page it will not be saved, and thus all of the snackbar message says 'History saved/updated', except for the location one which is already existed before.
> > Edit: I do found a way to trigger save user history upon select crops, should I add them when a crop is added?
> 
> Yes please. That way it is consistent with the browse section too

I have updated saving history when select/unselect crops. I haven't added for other selections since I think it's still efficient to save by step changes, but it's also possible to add these changes.

**Comment by Adamws33** [comment]
> > > > The first alert says "your location has been saved" and all of the rest say "History Updated". Can we update each of them to be a more clear message for what has just been updated?
> > > 
> > > 
> > > > One thing i noticed is that when i add crops from the browse and then hit restart and recall that history the crops i added are included in the history. But if i go through the get a recommendation and i add crops i still get the alert "[crop name] was added" but the crops are not getting saved to my history unless i navigate away from the page to my list before restarting.
> > > 
> > > 
> > > Currently the history is only saved upon page change so if you don't switch the page it will not be saved, and thus all of the snackbar message says 'History saved/updated', except for the location one which is already existed before.
> > > Edit: I do found a way to trigger save user history upon select crops, should I add them when a crop is added?
> > 
> > 
> > Yes please. That way it is consistent with the browse section too
> 
> I have updated saving history when select/unselect crops. I haven't added for other selections since I think it's still efficient to save by step changes, but it's also possible to add these changes.

When i add a crop to my list on both the browse and recommend section i get this error.  
image

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by Adamws33** [comment]
Ok one more thing i noticed. When you are saving a user history and you select a state.. then browse and you select a few crops.  you can then resrart and select that user history and it will populate in the Recommend section with those crops loaded.  This is fine because the user history prevents you from changing the state.  But the little 3 apears over the next buttons.  This isnt expected till the final step in the crop view pages.  Can you update the next button to only show this number when on that final step.
image

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://51.8.253.125:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
