### PR TITLE
Issue139: Header refactor

### PR DESCRIPTION
**Pull request by dearpriyankasa**
Removed the remaining unnecessary ternary operations from files under header

### CODE REVIEW

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.85.206.94:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.85.206.94:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.85.206.94:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by drewlearns** [comment]
Your review app has been deployed and is available at 'http://20.85.206.94:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
