### PR TITLE
Connect PSADropdown shared component to selector #709

### PR DESCRIPTION
**Pull request by ravighevariya10**
Replaced all the dropdowns with shared PSADropdown

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://48.216.197.63:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by YazidZidane — COMMENTED** [review]
Can you add all the `data-cy` props to SelectProps? They are used for testing

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,48.216.197.63,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://48.216.197.63:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://48.216.197.63:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by YazidZidane — APPROVED** [review]

**Pull request merged**
