### PR TITLE
Feature/672 button component

### PR DESCRIPTION
**Pull request by BrennenFa**
Replaced all existing buttons with the PSA Button and implemented a few general button styles

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,4.157.10.6,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.10.6:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by BrennenFa** [comment]
In CropCalendarView.js, I was not sure how to find the "Legend" button the main site

**Comment by YazidZidane** [comment]
This feature isn't strictly necessary, but I personally prefer to use `styled()` to create a customized button like this since this component is based on MUI `<Button/>` and have a lot of shared props.

**Comment by YazidZidane** [comment]
I also think that we should put custom components under `src/components` just for consistency.

**Comment by Adamws33** [comment]
> I also think that we should put custom components under `src/components` just for consistency.

I am not opposed to this. I asked him to put it in shared since these will eventually be getting shared with the rest of the tools.   I just thought it might be a better spot for it.  @mikahpinegar thoughts?

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.10.6:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://4.157.10.6:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
> > I also think that we should put custom components under `src/components` just for consistency.
> 
> I am not opposed to this. I asked him to put it in shared since these will eventually be getting shared with the rest of the tools. I just thought it might be a better spot for it. @mikahpinegar thoughts?

i would put them in /src/components

**Comment by BrennenFa** [comment]
> > > I also think that we should put custom components under `src/components` just for consistency.
> > 
> > 
> > I am not opposed to this. I asked him to put it in shared since these will eventually be getting shared with the rest of the tools. I just thought it might be a better spot for it. @mikahpinegar thoughts?
> 
> i would put them in /src/components

What should I call the new folder in components? Everything else in that directory is a folder

**Comment by Adamws33** [comment]
> > > > I also think that we should put custom components under `src/components` just for consistency.
> > > 
> > > 
> > > I am not opposed to this. I asked him to put it in shared since these will eventually be getting shared with the rest of the tools. I just thought it might be a better spot for it. @mikahpinegar thoughts?
> > 
> > 
> > i would put them in /src/components
> 
> What should I call the new folder in components? Everything else in that directory is a folder

per our slack conversation PSAComponents will work.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.114.172:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.114.172:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,135.237.114.172:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.114.172:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://135.237.114.172:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by YazidZidane — APPROVED** [review]

**Pull request merged**
