### PR TITLE
Feature/thumbnail images

### PR DESCRIPTION
**Pull request by Adamws33**
Updated all different APIS to use new data and begin to fill the application based on the data.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
smaller screens cause overlap of sidebar and calendar view 
overlap

**Comment by mikahpinegar** [comment]
sidebar categories are different now

**Comment by mikahpinegar** [comment]
lots of crops are missing scientific name in the cards in explorer

**Comment by mikahpinegar** [comment]
the following infosheets are broken for zone 6 in northeast 

infosheets that show no data:
- Clover, Balansa
- Clover, Berseem
- Cowpea
- Phacelia
- Sorgum-sudangrass
- Soybeans
- Sudangrass
- Sunflower
- Sunn hemp

infosheets that crash the app 
- Oats
- Oats, Black
- Oats, Spring
- Radish, Forage
- Rapeseed, Forage
- Triticale, Spring

**Comment by mikahpinegar** [comment]
missing zone 4 in the explorer

**Comment by mikahpinegar** [comment]
compare all has different categories for the list view page

**Comment by Adamws33** [comment]
> compare all has different categories for the list view page

Can you post a couple screen shots so i know more specifically what to look for?

**Comment by Adamws33** [comment]
> lots of crops are missing scientific name in the cards in explorer

this is a data issue.  I noticed this when i was testing.

**Comment by Adamws33** [comment]
> smaller screens cause overlap of sidebar and calendar view overlap

Yeah i had noticed this. i will get to this.  I prioritized this last just incase we came down to needing this version out asap for the videos.

**Comment by Adamws33** [comment]
> sidebar categories are different now

In what was should it be different that it shouldn't be? things are all built based on the data from the API should it be different.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
