### PR TITLE
Integrate shared header

### PR DESCRIPTION
**Pull request by YazidZidane**
- Integrate shared header component, remove previous one

- Updated related testing.

- Integrate shared theme for colors and font.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://,52.224.84.209,:,80,'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://52.224.84.209:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by Adamws33** [comment]
Can we put the buttons for the browse cover crops and get a recommendation in the header please? they need space between them and the infobar but adding extra space in would be too much. Lets move it to where the green box is.  

image

**Comment by Adamws33** [comment]
The space between the header and the top of the page is a little large can we reduce it by half?

**Comment by Adamws33** [comment]
on the selector the header looks like its indented from the top left corner.  compared to the implementation of the header on seedcalc can we push the title and logo more to the top left corner of the selector to mimic the position relative to the tool like seedcalc is.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://52.224.84.209:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://52.224.84.209:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Review by Adamws33 — APPROVED** [review]

**Pull request merged**
